import type { StyleValue } from 'vue';
import type { AppView, LibraryCollection, LibraryFilter } from '../composables/useLibraryNavigation';
import type { ArtistGroup, LocalFolderItem } from './library';
import type { DownloadItem, Track, UserPlaylist } from './music';
import type { OnlineSearchSnapshot } from './onlineSearch';
import type { PluginSearchTrack } from './plugin';

export interface AppMainContentProps {
  activeArtistName: string | null;
  activeCollection: LibraryCollection;
  activeFolderPath: string | null;
  activeLibraryFilter: LibraryFilter;
  activePlaylistId: string | null;
  activeTrack: Track | null;
  activeView: AppView;
  appGridStyle: StyleValue;
  artistGroups: ArtistGroup[];
  downloadedTrackKeys: string[];
  downloadItems: DownloadItem[];
  enablePlugins: boolean;
  favoriteTrackIds: number[];
  isAudioPlaying: boolean;
  isLibraryPanelMode: boolean;
  isLibraryVisible: boolean;
  isOnlineSearchOpen: boolean;
  isPreparingActiveTrack: boolean;
  isResizingLibraryPanel: boolean;
  isSidebarCollapsed: boolean;
  libraryMeta: { count: number; minutes: number };
  libraryTitle: string;
  localFolderTrackCount: number;
  localFolders: LocalFolderItem[];
  onlineActiveTrackKey: string | null;
  onlinePreparingTrackKey: string | null;
  onlineSearchError: string | null;
  pendingDownloadTrackKeys: string[];
  playbackSpectrumLevels: number[];
  playerError: string | null;
  playerQuery: string;
  playlists: UserPlaylist[];
  recentAddedTrackCount: number;
  shouldShowDownloadsMenu: boolean;
  shouldShowLibraryResizeHandle: boolean;
  visibleTracks: Track[];
}

export interface AppMainContentEmits {
  addDownloadedTrackToPlaylist: [item: DownloadItem];
  changePlaylistCover: [playlistId: string];
  chooseFolder: [];
  clearDownloadedItemRecord: [item: DownloadItem];
  createPlaylist: [];
  deleteDownloadedItem: [item: DownloadItem];
  downloadTrack: [track: Track];
  notify: [message: string, variant?: 'success' | 'error'];
  onlineSearchStarted: [];
  onlineSearchUpdated: [snapshot: OnlineSearchSnapshot];
  openArtistFromTrack: [artistName: string];
  openArtistsView: [];
  openDiscoverMusicView: [];
  openDownloadedItemFolder: [item: DownloadItem];
  openDownloadsView: [];
  openFavoritesView: [];
  openLocalFolderFromPanel: [path: string];
  openOnlineTrackContextMenu: [track: PluginSearchTrack, x: number, y: number];
  openPlaylistContextMenu: [playlist: UserPlaylist, x: number, y: number];
  openPlaylistView: [playlistId: string];
  openPluginsView: [];
  openRecentAdded: [];
  openRecentAddedFromPanel: [];
  openRecentPlayed: [];
  openScanDialog: [];
  openSettingsView: [];
  openThemeView: [];
  openTrackContextMenu: [track: Track, x: number, y: number];
  pauseDownloadItem: [item: DownloadItem];
  playDownloadedTrack: [track: Track];
  playFavoriteTracks: [];
  playOnlineTrack: [track: PluginSearchTrack];
  playTrack: [track: Track];
  queueDownloadedTrackNext: [item: DownloadItem];
  rescanLibrary: [];
  resumeDownloadItem: [item: DownloadItem];
  retryDownloadItem: [item: DownloadItem];
  returnToLocalLibrary: [];
  selectArtist: [artistName: string];
  selectTrack: [track: Track];
  startLibraryPanelResize: [event: PointerEvent];
  toggleFavoriteForTrack: [track: Track];
  toggleSidebarCollapsed: [];
  updatePlayerQuery: [value: string];
}

export interface AppMainContentListeners {
  onAddDownloadedTrackToPlaylist: (...args: AppMainContentEmits['addDownloadedTrackToPlaylist']) => void;
  onChangePlaylistCover: (...args: AppMainContentEmits['changePlaylistCover']) => void;
  onChooseFolder: () => void;
  onClearDownloadedItemRecord: (...args: AppMainContentEmits['clearDownloadedItemRecord']) => void;
  onCreatePlaylist: () => void;
  onDeleteDownloadedItem: (...args: AppMainContentEmits['deleteDownloadedItem']) => void;
  onDownloadTrack: (...args: AppMainContentEmits['downloadTrack']) => void;
  onOpenArtistFromTrack: (...args: AppMainContentEmits['openArtistFromTrack']) => void;
  onOpenArtistsView: () => void;
  onOpenDiscoverMusicView: () => void;
  onOpenDownloadedItemFolder: (...args: AppMainContentEmits['openDownloadedItemFolder']) => void;
  onOpenDownloadsView: () => void;
  onOpenFavoritesView: () => void;
  onOpenLocalFolderFromPanel: (...args: AppMainContentEmits['openLocalFolderFromPanel']) => void;
  onOpenOnlineTrackContextMenu: (...args: AppMainContentEmits['openOnlineTrackContextMenu']) => void;
  onOpenPlaylistContextMenu: (...args: AppMainContentEmits['openPlaylistContextMenu']) => void;
  onOpenPlaylistView: (...args: AppMainContentEmits['openPlaylistView']) => void;
  onOpenPluginsView: () => void;
  onOpenRecentAdded: () => void;
  onOpenRecentAddedFromPanel: () => void;
  onOpenRecentPlayed: () => void;
  onOpenScanDialog: () => void;
  onOpenSettingsView: () => void;
  onOpenThemeView: () => void;
  onOpenTrackContextMenu: (...args: AppMainContentEmits['openTrackContextMenu']) => void;
  onNotify: (...args: AppMainContentEmits['notify']) => void;
  onPauseDownloadItem: (...args: AppMainContentEmits['pauseDownloadItem']) => void;
  onPlayDownloadedTrack: (...args: AppMainContentEmits['playDownloadedTrack']) => void;
  onPlayFavoriteTracks: () => void;
  onPlayOnlineTrack: (...args: AppMainContentEmits['playOnlineTrack']) => void;
  onPlayTrack: (...args: AppMainContentEmits['playTrack']) => void;
  onQueueDownloadedTrackNext: (...args: AppMainContentEmits['queueDownloadedTrackNext']) => void;
  onRescanLibrary: () => void;
  onRetryDownloadItem: (...args: AppMainContentEmits['retryDownloadItem']) => void;
  onResumeDownloadItem: (...args: AppMainContentEmits['resumeDownloadItem']) => void;
  onReturnToLocalLibrary: () => void;
  onOnlineSearchStarted: () => void;
  onOnlineSearchUpdated: (...args: AppMainContentEmits['onlineSearchUpdated']) => void;
  onSelectArtist: (...args: AppMainContentEmits['selectArtist']) => void;
  onSelectTrack: (...args: AppMainContentEmits['selectTrack']) => void;
  onStartLibraryPanelResize: (...args: AppMainContentEmits['startLibraryPanelResize']) => void;
  onToggleFavoriteForTrack: (...args: AppMainContentEmits['toggleFavoriteForTrack']) => void;
  onToggleSidebarCollapsed: () => void;
  onUpdatePlayerQuery: (...args: AppMainContentEmits['updatePlayerQuery']) => void;
}
